CREATE TABLE IF NOT EXISTS User_Register(
    id VARCHAR(255) PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS User_Cpf(
    id VARCHAR(255) PRIMARY KEY,
    CPF VARCHAR(255) NOT NULL UNIQUE, 
    user_id VARCHAR(255),
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES User_Register(id)
);

CREATE TABLE IF NOT EXISTS User_Name(
    id VARCHAR(255) PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL UNIQUE,
    last_name VARCHAR(255) NOT NULL UNIQUE,
    user_id VARCHAR(255),
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES User_Register(id)
);

CREATE TABLE IF NOT EXISTS User_Birthday(
    id VARCHAR(255) PRIMARY KEY,
    birth_date DATE NOT NULL,
    user_id VARCHAR(255),
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES User_Register(id)
);

CREATE TABLE IF NOT EXISTS User_Phone(
    id VARCHAR(255) PRIMARY KEY,
    phone_number VARCHAR(16) UNIQUE NOT NULL,
    user_id VARCHAR(255),
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES User_Register(id)
);

CREATE TABLE IF NOT EXISTS User_Address(
    id VARCHAR(255) PRIMARY KEY,
	cep VARCHAR(10) UNIQUE NOT NULL,
	street VARCHAR(255) NOT NULL,
	number INT NOT NULL, 
	complement VARCHAR(255) NOT NULL,
	city VARCHAR(255) NOT NULL,
	state VARCHAR(2) NOT NULL,
	user_id VARCHAR(255),
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES User_Register(id)
);

CREATE TABLE IF NOT EXISTS Amount_Requested(
    id VARCHAR(255) PRIMARY KEY,
    amount_requested FLOAT, 
    user_id VARCHAR(255),
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES User_Register(id)
);